[package]
name = "dbi-d/devroblox"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
Knit = "sleitnick/knit@1.7.0"
Roact = "roblox/roact@1.4.4"
Trove = "sleitnick/trove@1.3.0"
Input = "sleitnick/input@2.3.0"
Signal = "sleitnick/signal@2.0.1"
Shake = "sleitnick/shake@1.1.0"
Timer = "sleitnick/timer@1.1.2"
RoactRodux = "roblox/roact-rodux@0.3.0"
Rodux = "roblox/rodux@3.0.0"
Hooks = "kampfkarren/roact-hooks@0.3.0"
Roduxhooks = "solarhorizon/rodux-hooks@0.3.1"
RoactSpring = "chriscerie/roact-spring@^1.1.6"
#Animation = "rivrs/animation-module@0.1.26"
#VFX = "release/vfx-module@0.0.11"

Networker = "leifstout/networker@0.3.0"


[server-dependencies]
Profileservice = "firebird702/profileservice@1.1.0"